export const TextData = {
    about: {
        details: [
            { header: "TITLE", value: "Software Development Engineer II" },
            { header: "EXPERIENCE", value: "3 Years" },
            { header: "DOMAIN", value: "Full-Stack, Cloud, DevOps" },
            { header: "SCHOOL", value: "University of Maryland, College Park" },
            {
                header: "HOBBIES",
                value: "Building PCs, online games, & centering divs",
            },
            { header: "DEGREE", value: "Bachelor of Science" },
        ],
    },
    placesVisited: [
        {
            src: "https://fastly.picsum.photos/id/1082/1920/1080.jpg?hmac=R-FW85Ql3APTWaXe09q_4kjyylVzjB_EySE3UwZOrLU",
            alt: "some image",
        },
        {
            src: "https://fastly.picsum.photos/id/424/1920/1080.jpg?hmac=JzwsjH5Hrdi5_3bo5flu2W0XaDry_ZmPotU9x0KEja4",
            alt: "some image",
        },
        {
            src: "https://fastly.picsum.photos/id/1082/1920/1080.jpg?hmac=R-FW85Ql3APTWaXe09q_4kjyylVzjB_EySE3UwZOrLU",
            alt: "some image",
        },
        {
            src: "https://fastly.picsum.photos/id/424/1920/1080.jpg?hmac=JzwsjH5Hrdi5_3bo5flu2W0XaDry_ZmPotU9x0KEja4",
            alt: "some image",
        },
        {
            src: "https://fastly.picsum.photos/id/1082/1920/1080.jpg?hmac=R-FW85Ql3APTWaXe09q_4kjyylVzjB_EySE3UwZOrLU",
            alt: "some image",
        },
        {
            src: "https://fastly.picsum.photos/id/424/1920/1080.jpg?hmac=JzwsjH5Hrdi5_3bo5flu2W0XaDry_ZmPotU9x0KEja4",
            alt: "some image",
        },
        {
            src: "https://fastly.picsum.photos/id/424/1920/1080.jpg?hmac=JzwsjH5Hrdi5_3bo5flu2W0XaDry_ZmPotU9x0KEja4",
            alt: "some image",
        },
    ],
    tech: [
        {
            title: "FRONTEND",
            technologies: [
                ,
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
            ],
        },
        {
            title: "BACKEND",
            technologies: [
                ,
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
            ],
        },
        {
            title: "CLOUD",
            technologies: [
                ,
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
            ],
        },
        {
            title: "ML / AI",
            technologies: [
                ,
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
                "React",
                "HTML / CSS",
                "NextJS",
                "Playwright",
                "Storybook",
            ],
        },
    ],
    experience: [
        {
            company: "AMAZON",
            title: "Software Development Engineer",
            summary:
                "Riot Games, the company that acts as the main distributor of the video game, has been in charge of managing video game, has been in charge of Riot Games, the company that acts as the main distributor of the video game, has been in charge of managing video game, has been in charge of ",
            team: "AWS App Mesh",
            timeline: "June - August 2019",
            imgUrl: "https://fastly.picsum.photos/id/675/400/500.jpg?hmac=2X5NSSStMEerYxgHCfn6vHVAbWFT2X8bbn36EsQvl0Y",
            imgAlt: "Image showing Amazon product website for a video game",
        },
        {
            company: "AMAZON",
            title: "Software Development Engineer",
            summary:
                "Riot Games, the company that acts as the main distributor of the video game, has been in charge of managing video game, has been in charge of Riot Games, the company that acts as the main distributor of the video game, has been in charge of managing video game, has been in charge of ",
            team: "AWS App Mesh",
            timeline: "June - August 2019",
            imgUrl: "https://fastly.picsum.photos/id/675/400/500.jpg?hmac=2X5NSSStMEerYxgHCfn6vHVAbWFT2X8bbn36EsQvl0Y",
            imgAlt: "Image showing Amazon product website for a video game",
        },
    ],
    projects: {},
};
